/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useCubeTexture, useTexture} from '@react-three/drei'

export function CapsuleBus(props) {
  const { nodes, materials } = useGLTF('/capsuleBus.gltf');
  const busBottomTex = useTexture('BusBottom.png');

  const metalTexture = useCubeTexture(
    ["px.png", "nx.png", "py.png", "ny.png", "pz.png", "nz.png"],
    {path: "hdr/"}
  );

  return (
    <>
    {props.displayNo == 1 &&  
   <group {...props} dispose={null}>
      <mesh geometry={nodes.Sphere.geometry} material={materials.Glass} scale={[1, 1, 1.46]} >
        <meshBasicMaterial opacity={0.40} transparent/>
      </mesh>
      <mesh geometry={nodes.Sphere001.geometry} material={materials.BusBottom} scale={[1, 1, 1.46]} >
        <meshBasicMaterial envMap={metalTexture} map={busBottomTex} reflectivity={0.9} />
      </mesh>
      <mesh geometry={nodes.Sphere002.geometry} material={materials.Tyre} position={[0.01, -1.25, 1.89]} rotation={[-Math.PI, 0, 0]} scale={[-0.06, -0.27, -0.27]} />
      <mesh geometry={nodes.Cube.geometry} material={materials.Seat} position={[0.35, -0.11, 0.9]} rotation={[Math.PI, 0, Math.PI]} scale={[0.31, 0.34, 0.31]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials.Seat} position={[-0.35, -0.11, 0.9]} rotation={[Math.PI, 0, Math.PI]} scale={[0.31, 0.34, 0.31]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials.Seat} position={[0.35, -0.11, 0.1]} rotation={[Math.PI, 0, Math.PI]} scale={[0.31, 0.34, 0.31]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials.Seat} position={[-0.35, -0.11, 0.1]} rotation={[Math.PI, 0, Math.PI]} scale={[0.31, 0.34, 0.31]} />
      <mesh geometry={nodes.Cube004.geometry} material={materials.Seat} position={[0.35, -0.11, -0.72]} rotation={[Math.PI, 0, Math.PI]} scale={[0.31, 0.34, 0.31]} />
      <mesh geometry={nodes.Cube005.geometry} material={materials.Seat} position={[-0.35, -0.11, -0.72]} rotation={[Math.PI, 0, Math.PI]} scale={[0.31, 0.34, 0.31]} />
      <mesh geometry={nodes.Cube006.geometry} material={materials.Seat} position={[0.35, -0.11, -1.45]} rotation={[Math.PI, 0, Math.PI]} scale={[0.31, 0.34, 0.31]} />
      <mesh geometry={nodes.Cube007.geometry} material={materials.Seat} position={[-0.35, -0.11, -1.45]} rotation={[Math.PI, 0, Math.PI]} scale={[0.31, 0.34, 0.31]} />
      <mesh geometry={nodes.Cube008.geometry} material={materials.Seat} position={[0.35, -0.11, 1.5]} rotation={[Math.PI, 0, Math.PI]} scale={[0.31, 0.34, 0.31]} />
      <mesh geometry={nodes.Cube009.geometry} material={materials.Seat} position={[-0.35, -0.11, 1.5]} rotation={[Math.PI, 0, Math.PI]} scale={[0.31, 0.34, 0.31]} />
      <mesh geometry={nodes.Cylinder.geometry} material={materials.HeadLight} position={[0.01, 0.2, 2.7]} rotation={[1.13, 0, 0]} scale={[0.1, 0.06, 0.1]} />
    </group>
    }
    </>
  )
}

useGLTF.preload('/capsuleBus.gltf')
