/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useCubeTexture, useTexture} from '@react-three/drei'


export function Podjet(props) {
  const { nodes, materials } = useGLTF('/Podjet.gltf');
  const metalTexture = useCubeTexture(
    ["px.png", "nx.png", "py.png", "ny.png", "pz.png", "nz.png"],
    {path: "hdr/"}
  );

    const bodyTex = useTexture('Body.png');
    const pipeL = useTexture('pipeL.png');
    const pipeR = useTexture('pipeR.png');

  return (
    <>
   {props.displayNo == 0 &&  
   <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.Body} scale={[2.49, 0.53, 6.01]} >
        <meshBasicMaterial envMap={metalTexture} map={bodyTex} reflectivity={0.8} /> 
      </mesh>
      <mesh geometry={nodes.Sphere.geometry} material={materials['Material.002']} position={[5.08, 1, 2.71]} >
        <meshBasicMaterial color={0x000055} opacity={0.65} transparent/> 
      </mesh>
      <mesh geometry={nodes.Cylinder.geometry} material={materials.pipeL} position={[-3.34, -0.01, 3.07]} rotation={[1.65, -1.05, 0.1]} scale={[1.01, 4.61, 1.02]} >
        <meshBasicMaterial envMap={metalTexture} map={pipeL} reflectivity={0.8} /> 
      </mesh>
      <mesh geometry={nodes.Cylinder001.geometry} material={materials['Material.001']} position={[2.41, -0.01, 3.07]} rotation={[1.27, -1.02, -0.34]} scale={[1.01, 4.61, 1.02]} >
       <meshBasicMaterial envMap={metalTexture} map={pipeR} reflectivity={0.8} /> 
      </mesh>
    </group>
    }
    </>
  )
}

useGLTF.preload('/Podjet.gltf')
